### ISSUE TITLE
label?

### ISSUE THREAD

**Issue by luciostuder** [RodrigoDias04/RodrigoDias04.github.io#2]
https://github.com/RodrigoDias04/RodrigoDias04.github.io/blob/59628913f0c29aba0e76c2be85888f8050e4d0db/lab3/quizz.html#L40

este label nao esta associado a nenhum input. podes usar varias coisas:
- paragrafo
- crias um fieltset que envolve todos radios, e poes o texto desse label na legend?

**Comment by RodrigoDias04** [comment]
resolvido
